# Default values for gitaly.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  gitaly:
    enabled: true
    internal:
      names: ["default"]
    external: []
    authToken:
      secret: "gitaly-secrets"
      key: "token"
    hooks: {}
    tls:
      enabled: true
      secretName: "cm-gitlab-tls"
    service:
      externalPort: 8075
      internalPort: 8075
      tls:
        externalPort: 8076
        internalPort: 8076
      type: ClusterIP
      clusterIP: None


gitlab:
  gitaly:
    image:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitaly
        # pullPolicy: IfNotPresent

        # tag: master
    annotations:
      fzen: "gitlab.gitaly"
      reloader.stakater.com/auto: "true"

    extraInitContainers: |
      - name: test-init-cron
        image: alpine:latest
        command: ["/bin/ash", "-c", "/tmp/init.sh"]
        volumeMounts:
          - mountPath: /source
            name: repo-data
          - mountPath: /dest
            name: repo-data-backup
          - mountPath: /tmp/
            name: gitaly-data-init

    extraContainers: |
      - name: cron-job
        image: alpine:latest
        command: ["/usr/sbin/crond", "-f"]
        securityContext:
          runAsUser: 0
        volumeMounts:
          - mountPath: /source
            name: repo-data
          - mountPath: /etc/periodic/hourly/
            name: gitaly-cron-backup
          - mountPath: /backup/
            name: repo-data-backup

    extraVolumes: |
      - name: repo-data-backup
        persistentVolumeClaim:
          claimName: repo-data-backup-gitaly-0
      - name: gitaly-data-init
        configMap:
          name: gitaly-data-init
          items:
          - key: init.sh
            path: init.sh
            mode: 0755
      - name: gitaly-cron-backup
        configMap:
          name: gitaly-cron-backup
          items:
          - key: backup
            path: backup
            mode: 0755

    metrics:
      enabled: true
      port: 9237
      path: /metrics
      serviceMonitor:
        enabled: false
        additionalLabels: { }
        endpointConfig: { }
    persistence:
      enabled: false
      storageClass: "nfs-client"
      accessMode: ReadWriteOnce
      size: 10Gi
      subPath: ""
      matchLabels: {}
      matchExpressions: []
      annotations:
        nfs.io/storage-path: "gitaly_data"
      labels: {}

    # Gitaly built-in cgroups, spawns Git processes into a cgroup per repository, protecting the service/pod from OOM events
    # ref: https://docs.gitlab.com/ee/administration/gitaly/configure_gitaly.html#control-groups
    cgroups:
      enabled: false
      initContainer:
        image:
          repository: registry.gitlab.com/gitlab-org/build/cng/gitaly-init-cgroups
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      mountpoint: '{% file.Read "/etc/gitlab-secrets/gitaly-pod-cgroup" | strings.TrimSpace %}'
      hierarchyRoot: gitaly
      # memoryBytes:
      # cpuShares:
      # cpuQuotaUs:
      repositories: {}
        # count:
        # memoryBytes:
        # cpuShares:
        # cpuQuotaUs:
        # maxCgroupsPerRepo:
    # Gitaly shutdown grace period, how long to wait for in-flight requests to complete (seconds)
    # Pod `terminationGracePeriodSeconds` is set to this value + 5 seconds
    gracefulRestartTimeout: 25
    # default enable gomemlimit to avoid gc related OOM errors
    gomemlimit:
      enabled: true
    logging:
      format: "json"
      level: "warn"
        # sentryDsn:
        # sentryEnvironment:
    resources:
#      limits:
#        cpu: 500m
#        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi

    git: {}
      # catFileCacheSize:
      ## Amend the default configuration Gitaly is using when spawning Git
      ## commands. Accepts configuration as documented in git-config(1).
      # config:
      #   - {key: "pack.threads", value: 4}

    # Allows process namespace sharing within the pod
    # This makes processes in a container visible to all other containers in the same pod.
    shareProcessNamespace: false

    ## For PodDisruptionBudget, how many pods can be unavailable at one time
    maxUnavailable: 1

    ## Allow to overwrite under which User and Group Pod will be running.
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
      # fsGroupChangePolicy: OnRootMismatch

    ## Allow to overwrite the specific security context under which the gitaly container is running.
    containerSecurityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop: ["ALL"]

    ## Enable deployment to use a serviceAccount
    serviceAccount:
      enabled: false
      create: false
      annotations: {}
      ## Used for local override of global ServiceAccount token mounting
      # automountServiceAccountToken: false
      ## Name to be used for serviceAccount, otherwise defaults to chart fullname
      # name:

    statefulset:
      strategy: {}
      livenessProbe:
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 3
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        initialDelaySeconds: 0
        periodSeconds: 5
        timeoutSeconds: 3
        successThreshold: 1
        failureThreshold: 3
      startupProbe:
        enabled: true
        initialDelaySeconds: 1
        periodSeconds: 1
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 60

    affinity:
      podAntiAffinity:
        topologyKey:
      nodeAffinity:
        key:
        values:

    ## Enable the Gitaly pack-objects cache
    ## ref: https://docs.gitlab.com/ee/administration/gitaly/configure_gitaly.html#pack-objects-cache
    packObjectsCache: {}
    #  enabled: false
    #  dir: "/home/git/repositories/+gitaly/PackObjectsCache"
    #  max_age: 5m

    ## Enable Gitaly to GPG sign all commits created by GitLab
    ## ref: https://docs.gitlab.com/ee/administration/gitaly/configure_gitaly.html#configure-commit-signing-for-gitlab-ui-commits
    gpgSigning: {}
      # enabled: false
    # secret: glGPG
    # key:

    backup: {}
      # goCloudUrl:

    init:
      image: {}
        # repository:
      # tag:
      resources:
        requests:
          cpu: 250m
      containerSecurityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop: [ "ALL" ]


























## Support for tolerations for pod scheduling
tolerations: []

## The Gitaly StatefulSet's priorityClassName
# priorityClassName:





prometheus: {}
# grpcLatencyBuckets: "[1.0, 1.5, 2.0, 2.5]"




## Enable prometheus metrics and set the port to scrape the
## container on.


## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##







